### ISSUE TITLE
Feature suggestion: Support for portrait-style box art (i.e.: Japanese games)

### ISSUE THREAD

**Issue by PW5190** [Polprzewodnikowy/N64FlashcartMenu#124]
### Description

I have a suggestion. Last night, I discussed in the N64brew Discord about using portrait-style (vertical) box arts on the N64 Flashcart Menu. While North American and PAL games use horizontal, landscape-style box arts, Japanese games use vertical, portrait-style box arts. Any chance it could be implemented in the foreseeable future? We could still use the two-letter ID or three-letter ID method for filenames. It can be useful for games exclusive to Japan, like the Custom Robo games.

So, what do you think of this idea?

### How to solve the problem

Find the correct resolution for Japanese box arts, and allow them to use the same two-letter and three-letter ID method for filenames, with the file extension still being `.png`.

**Comment by networkfusion** [comment]
Please can you link to some sample images? Ideally a download location that contains a full boxset. 

Because we are able to match against 3 chars (and could even add code to check against the forth), it should not be too hard to check the ROM region char and rotate by 90 deg. Although I am worried that this will cause problems with the layout of the ROM info screen.

**Comment by networkfusion** [comment]
#126 seems to work towards this.

**Comment by networkfusion** [comment]
Merged to main, so closing.
