### ISSUE TITLE
Add PixelFX N64Digital/GEM support.

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/N64FlashcartMenu#28]
### Description

Add support for PixelFX ROM ID detection to the menu as supported by ED64 and 64Drive menus.

### How to solve the problem

Send the ROM CRC over the SI. See https://gitlab.com/pixelfx-public/n64-game-id

**Comment by networkfusion** [comment]
Theoretically, the only thing that is needed is the following before booting the ROM (using `libdragon.h`):

```
/**
 * @brief Send ROM info to the PixelFx N64Digital Mod.
 *
 * Send a command to the mod over the SI bus.
 *
 * @param[in]  checksum
 *             The checksum of the ROM obtained from the file header.
 * @param[in]  media_type
 *             The media type of the ROM obtained from the file header.
 * @param[in]  destination_market
 *             The destination market of the ROM obtained from the file header.
 */
void pfx_mod_send_rom_info(uint8_t* checksum, uint8_t media_type, uint8_t destination_market)
{
    int pfx_accessory_controller = 0;
    int pfx_accessory_cmd = 0x1D;

    uint8_t out[10];
    uint8_t in[64];

    memcpy(out, checksum, 8);
    
    out[8] = media_type;
    out[9] = destination_market;

    execute_raw_command( pfx_accessory_controller, pfx_accessory_cmd, sizeof(out), 0, out, in );
}
```

**Comment by Polprzewodnikowy** [comment]
Implemented in https://github.com/Polprzewodnikowy/N64FlashcartMenu/commit/5d8ebf9200b2b8539cbb12639185304d9aae162e

**Comment by mitchellcairns** [comment]
I wanted to make a note here @Polprzewodnikowy ; I'm a gamepad developer, and began having issues with compatibility after updating the SC64 firmware on my flashcart.

After doing some digging with a logic analyzer and seeing the mystery command, searching for it and finding that it was related to game title ID as a custom implementation, everything works fine after patching my gamepad firmware.

I imagine there are other third party gamepads on the market that may not respond well to the command. 

Could this be implemented as a configuration option to enable/disable? I believe that recent reports of crashing with Analogue 64 may be related to this: https://www.reddit.com/r/AnalogueInc/comments/1temu0c/summercart_64_crashing_on_8bitdo_24_ghz/

I do think that a sane default would be 'off' since it may not be obvious why it isn't working when it does fail.

**Comment by Polprzewodnikowy** [comment]
The correct behavior for a gamepad is to ignore unknown commands just like OEM controllers do. Do the right thing and add command filtering to your custom device - any homebrew ROM on N64 can send whatever it wants on the Joybus, in turn crashing your gamepad. AFAIK only 8bitdo controllers had issue with this and it's been fixed on their end.

**Comment by mitchellcairns** [comment]
In my case it was not a crash, because it's a microcontroller and not an ASIC (like many homebrew gamepads) there is a recovery state; the game then registers the gamepad as disconnected since the next probe/poll gets missed. 

My point in bringing this up is that there may be other accessories etc which would have the same behavior and cannot be patched out. 

In any case, I've already done "the right thing", games can send any data over joybus, doesn't mean they should, especially at boot time.
